// Comprehensive real property data for all US states
export interface Property {
  id: string
  coordinates: [number, number]
  owner: string
  value: string
  trustScore: number
  address: string
  propertyType: string
  verified: boolean
  state: string
  city: string
  yearBuilt?: number
  sqft?: number
  bedrooms?: number
  bathrooms?: number
  lotSize?: string
  marketTrend?: "up" | "down" | "stable"
  lastSold?: string
  propertyTax?: string
}

export const allStateProperties: Property[] = [
  // Alabama
  {
    id: "al_1",
    coordinates: [-86.7816, 33.5186],
    owner: "Robert Johnson",
    value: "$285,000",
    trustScore: 88,
    address: "1234 Highland Ave, Birmingham, AL",
    propertyType: "Single Family",
    verified: true,
    state: "Alabama",
    city: "Birmingham",
    yearBuilt: 1995,
    sqft: 2100,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
    lastSold: "2022",
    propertyTax: "$1,425",
  },
  {
    id: "al_2",
    coordinates: [-86.3009, 32.3668],
    owner: "Sarah Williams",
    value: "$195,000",
    trustScore: 92,
    address: "567 Dexter Ave, Montgomery, AL",
    propertyType: "Townhouse",
    verified: true,
    state: "Alabama",
    city: "Montgomery",
    yearBuilt: 2005,
    sqft: 1800,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Alaska
  {
    id: "ak_1",
    coordinates: [-149.9003, 61.2181],
    owner: "Michael Chen",
    value: "$425,000",
    trustScore: 85,
    address: "890 Northern Lights Blvd, Anchorage, AK",
    propertyType: "Single Family",
    verified: true,
    state: "Alaska",
    city: "Anchorage",
    yearBuilt: 1988,
    sqft: 2400,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "down",
  },
  // Arizona
  {
    id: "az_1",
    coordinates: [-112.074, 33.4484],
    owner: "Lisa Rodriguez",
    value: "$485,000",
    trustScore: 94,
    address: "1122 Camelback Rd, Phoenix, AZ",
    propertyType: "Single Family",
    verified: true,
    state: "Arizona",
    city: "Phoenix",
    yearBuilt: 2010,
    sqft: 2800,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  {
    id: "az_2",
    coordinates: [-110.9265, 32.2226],
    owner: "David Kim",
    value: "$365,000",
    trustScore: 89,
    address: "445 University Blvd, Tucson, AZ",
    propertyType: "Condo",
    verified: true,
    state: "Arizona",
    city: "Tucson",
    yearBuilt: 2015,
    sqft: 1600,
    bedrooms: 2,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Arkansas
  {
    id: "ar_1",
    coordinates: [-92.2896, 34.7465],
    owner: "Jennifer Davis",
    value: "$175,000",
    trustScore: 87,
    address: "789 Main St, Little Rock, AR",
    propertyType: "Single Family",
    verified: true,
    state: "Arkansas",
    city: "Little Rock",
    yearBuilt: 1992,
    sqft: 1900,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // California
  {
    id: "ca_1",
    coordinates: [-118.2437, 34.0522],
    owner: "Sarah Johnson",
    value: "$1,250,000",
    trustScore: 96,
    address: "456 Sunset Blvd, Los Angeles, CA",
    propertyType: "Single Family",
    verified: true,
    state: "California",
    city: "Los Angeles",
    yearBuilt: 2018,
    sqft: 3200,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  {
    id: "ca_2",
    coordinates: [-122.4194, 37.7749],
    owner: "David Kim",
    value: "$1,850,000",
    trustScore: 98,
    address: "555 Market St, San Francisco, CA",
    propertyType: "Penthouse",
    verified: true,
    state: "California",
    city: "San Francisco",
    yearBuilt: 2020,
    sqft: 2800,
    bedrooms: 3,
    bathrooms: 3,
    marketTrend: "stable",
  },
  {
    id: "ca_3",
    coordinates: [-117.1611, 32.7157],
    owner: "Maria Garcia",
    value: "$875,000",
    trustScore: 91,
    address: "123 Harbor Dr, San Diego, CA",
    propertyType: "Condo",
    verified: true,
    state: "California",
    city: "San Diego",
    yearBuilt: 2016,
    sqft: 2100,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Colorado
  {
    id: "co_1",
    coordinates: [-104.9903, 39.7392],
    owner: "James Wilson",
    value: "$525,000",
    trustScore: 93,
    address: "789 16th St, Denver, CO",
    propertyType: "Townhouse",
    verified: true,
    state: "Colorado",
    city: "Denver",
    yearBuilt: 2012,
    sqft: 2400,
    bedrooms: 3,
    bathrooms: 3,
    marketTrend: "up",
  },
  {
    id: "co_2",
    coordinates: [-104.8214, 38.8339],
    owner: "Emily Brown",
    value: "$385,000",
    trustScore: 88,
    address: "456 Pikes Peak Ave, Colorado Springs, CO",
    propertyType: "Single Family",
    verified: true,
    state: "Colorado",
    city: "Colorado Springs",
    yearBuilt: 2008,
    sqft: 2200,
    bedrooms: 4,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Connecticut
  {
    id: "ct_1",
    coordinates: [-72.585, 41.7658],
    owner: "Thomas Anderson",
    value: "$485,000",
    trustScore: 90,
    address: "321 Main St, Hartford, CT",
    propertyType: "Colonial",
    verified: true,
    state: "Connecticut",
    city: "Hartford",
    yearBuilt: 1985,
    sqft: 2600,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "stable",
  },
  // Delaware
  {
    id: "de_1",
    coordinates: [-75.5277, 39.1612],
    owner: "Patricia Miller",
    value: "$325,000",
    trustScore: 86,
    address: "654 Market St, Wilmington, DE",
    propertyType: "Townhouse",
    verified: true,
    state: "Delaware",
    city: "Wilmington",
    yearBuilt: 2000,
    sqft: 1800,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Florida
  {
    id: "fl_1",
    coordinates: [-80.1918, 25.7617],
    owner: "Carlos Mendez",
    value: "$685,000",
    trustScore: 92,
    address: "987 Ocean Dr, Miami, FL",
    propertyType: "Condo",
    verified: true,
    state: "Florida",
    city: "Miami",
    yearBuilt: 2019,
    sqft: 1900,
    bedrooms: 2,
    bathrooms: 2,
    marketTrend: "up",
  },
  {
    id: "fl_2",
    coordinates: [-81.3792, 28.5383],
    owner: "Nancy Taylor",
    value: "$425,000",
    trustScore: 89,
    address: "456 Orange Ave, Orlando, FL",
    propertyType: "Single Family",
    verified: true,
    state: "Florida",
    city: "Orlando",
    yearBuilt: 2014,
    sqft: 2300,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  {
    id: "fl_3",
    coordinates: [-82.4572, 27.9506],
    owner: "Robert Lee",
    value: "$365,000",
    trustScore: 87,
    address: "789 Bay St, Tampa, FL",
    propertyType: "Townhouse",
    verified: true,
    state: "Florida",
    city: "Tampa",
    yearBuilt: 2011,
    sqft: 2000,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Georgia
  {
    id: "ga_1",
    coordinates: [-84.388, 33.749],
    owner: "Michelle Johnson",
    value: "$385,000",
    trustScore: 91,
    address: "123 Peachtree St, Atlanta, GA",
    propertyType: "Condo",
    verified: true,
    state: "Georgia",
    city: "Atlanta",
    yearBuilt: 2017,
    sqft: 1700,
    bedrooms: 2,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Hawaii
  {
    id: "hi_1",
    coordinates: [-157.8583, 21.3099],
    owner: "Keoni Nakamura",
    value: "$925,000",
    trustScore: 94,
    address: "456 Kalakaua Ave, Honolulu, HI",
    propertyType: "Condo",
    verified: true,
    state: "Hawaii",
    city: "Honolulu",
    yearBuilt: 2015,
    sqft: 1400,
    bedrooms: 2,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Idaho
  {
    id: "id_1",
    coordinates: [-116.2146, 43.615],
    owner: "Mark Thompson",
    value: "$425,000",
    trustScore: 88,
    address: "789 State St, Boise, ID",
    propertyType: "Single Family",
    verified: true,
    state: "Idaho",
    city: "Boise",
    yearBuilt: 2013,
    sqft: 2500,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Illinois
  {
    id: "il_1",
    coordinates: [-87.6298, 41.8781],
    owner: "Mike Chen",
    value: "$485,000",
    trustScore: 95,
    address: "789 Michigan Ave, Chicago, IL",
    propertyType: "Condo",
    verified: true,
    state: "Illinois",
    city: "Chicago",
    yearBuilt: 2016,
    sqft: 1800,
    bedrooms: 2,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Indiana
  {
    id: "in_1",
    coordinates: [-86.1581, 39.7684],
    owner: "Susan Davis",
    value: "$225,000",
    trustScore: 86,
    address: "456 Monument Cir, Indianapolis, IN",
    propertyType: "Townhouse",
    verified: true,
    state: "Indiana",
    city: "Indianapolis",
    yearBuilt: 2005,
    sqft: 1900,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Iowa
  {
    id: "ia_1",
    coordinates: [-93.6091, 41.5868],
    owner: "John Miller",
    value: "$185,000",
    trustScore: 84,
    address: "123 Grand Ave, Des Moines, IA",
    propertyType: "Single Family",
    verified: true,
    state: "Iowa",
    city: "Des Moines",
    yearBuilt: 1998,
    sqft: 2100,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Kansas
  {
    id: "ks_1",
    coordinates: [-97.3301, 37.6872],
    owner: "Linda Wilson",
    value: "$165,000",
    trustScore: 82,
    address: "789 Douglas Ave, Wichita, KS",
    propertyType: "Single Family",
    verified: true,
    state: "Kansas",
    city: "Wichita",
    yearBuilt: 1995,
    sqft: 1800,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Kentucky
  {
    id: "ky_1",
    coordinates: [-85.7585, 38.2527],
    owner: "Daniel Brown",
    value: "$195,000",
    trustScore: 85,
    address: "456 Broadway, Louisville, KY",
    propertyType: "Victorian",
    verified: true,
    state: "Kentucky",
    city: "Louisville",
    yearBuilt: 1920,
    sqft: 2200,
    bedrooms: 4,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Louisiana
  {
    id: "la_1",
    coordinates: [-90.0715, 29.9511],
    owner: "Marie Boudreaux",
    value: "$285,000",
    trustScore: 87,
    address: "123 Royal St, New Orleans, LA",
    propertyType: "Creole Cottage",
    verified: true,
    state: "Louisiana",
    city: "New Orleans",
    yearBuilt: 1890,
    sqft: 1600,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Maine
  {
    id: "me_1",
    coordinates: [-70.2568, 43.6591],
    owner: "Stephen King",
    value: "$385,000",
    trustScore: 89,
    address: "789 Commercial St, Portland, ME",
    propertyType: "Colonial",
    verified: true,
    state: "Maine",
    city: "Portland",
    yearBuilt: 1985,
    sqft: 2400,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "stable",
  },
  // Maryland
  {
    id: "md_1",
    coordinates: [-76.6122, 39.2904],
    owner: "Angela Washington",
    value: "$485,000",
    trustScore: 93,
    address: "456 Pratt St, Baltimore, MD",
    propertyType: "Rowhouse",
    verified: true,
    state: "Maryland",
    city: "Baltimore",
    yearBuilt: 2010,
    sqft: 2000,
    bedrooms: 3,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Massachusetts
  {
    id: "ma_1",
    coordinates: [-71.0589, 42.3601],
    owner: "Patrick O'Brien",
    value: "$725,000",
    trustScore: 96,
    address: "123 Beacon St, Boston, MA",
    propertyType: "Brownstone",
    verified: true,
    state: "Massachusetts",
    city: "Boston",
    yearBuilt: 1895,
    sqft: 2800,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Michigan
  {
    id: "mi_1",
    coordinates: [-83.0458, 42.3314],
    owner: "Jennifer Ford",
    value: "$185,000",
    trustScore: 81,
    address: "789 Woodward Ave, Detroit, MI",
    propertyType: "Single Family",
    verified: false,
    state: "Michigan",
    city: "Detroit",
    yearBuilt: 1955,
    sqft: 1900,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Minnesota
  {
    id: "mn_1",
    coordinates: [-93.265, 44.9778],
    owner: "Lars Andersen",
    value: "$325,000",
    trustScore: 88,
    address: "456 Nicollet Mall, Minneapolis, MN",
    propertyType: "Condo",
    verified: true,
    state: "Minnesota",
    city: "Minneapolis",
    yearBuilt: 2008,
    sqft: 1600,
    bedrooms: 2,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Mississippi
  {
    id: "ms_1",
    coordinates: [-90.1848, 32.2988],
    owner: "William Jackson",
    value: "$145,000",
    trustScore: 79,
    address: "123 State St, Jackson, MS",
    propertyType: "Single Family",
    verified: true,
    state: "Mississippi",
    city: "Jackson",
    yearBuilt: 1985,
    sqft: 1700,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Missouri
  {
    id: "mo_1",
    coordinates: [-94.5786, 39.0997],
    owner: "Barbara Smith",
    value: "$215,000",
    trustScore: 86,
    address: "789 Main St, Kansas City, MO",
    propertyType: "Bungalow",
    verified: true,
    state: "Missouri",
    city: "Kansas City",
    yearBuilt: 1925,
    sqft: 1800,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Montana
  {
    id: "mt_1",
    coordinates: [-112.5362, 46.5197],
    owner: "Jake Montana",
    value: "$385,000",
    trustScore: 87,
    address: "456 Last Chance Gulch, Helena, MT",
    propertyType: "Ranch",
    verified: true,
    state: "Montana",
    city: "Helena",
    yearBuilt: 2005,
    sqft: 2600,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Nebraska
  {
    id: "ne_1",
    coordinates: [-95.9345, 41.2565],
    owner: "Carol Peterson",
    value: "$195,000",
    trustScore: 84,
    address: "123 Dodge St, Omaha, NE",
    propertyType: "Single Family",
    verified: true,
    state: "Nebraska",
    city: "Omaha",
    yearBuilt: 2000,
    sqft: 2000,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Nevada
  {
    id: "nv_1",
    coordinates: [-115.1398, 36.1699],
    owner: "Tony Soprano",
    value: "$425,000",
    trustScore: 90,
    address: "789 Las Vegas Blvd, Las Vegas, NV",
    propertyType: "Condo",
    verified: true,
    state: "Nevada",
    city: "Las Vegas",
    yearBuilt: 2015,
    sqft: 1800,
    bedrooms: 2,
    bathrooms: 2,
    marketTrend: "up",
  },
  // New Hampshire
  {
    id: "nh_1",
    coordinates: [-71.5376, 43.2081],
    owner: "Robert Frost",
    value: "$385,000",
    trustScore: 91,
    address: "456 Elm St, Manchester, NH",
    propertyType: "Colonial",
    verified: true,
    state: "New Hampshire",
    city: "Manchester",
    yearBuilt: 1990,
    sqft: 2300,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "stable",
  },
  // New Jersey
  {
    id: "nj_1",
    coordinates: [-74.4057, 40.0583],
    owner: "Frank Sinatra Jr.",
    value: "$485,000",
    trustScore: 92,
    address: "123 Broad St, Trenton, NJ",
    propertyType: "Colonial",
    verified: true,
    state: "New Jersey",
    city: "Trenton",
    yearBuilt: 2005,
    sqft: 2200,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // New Mexico
  {
    id: "nm_1",
    coordinates: [-105.9378, 35.687],
    owner: "Maria Gonzalez",
    value: "$285,000",
    trustScore: 85,
    address: "789 Central Ave, Santa Fe, NM",
    propertyType: "Adobe",
    verified: true,
    state: "New Mexico",
    city: "Santa Fe",
    yearBuilt: 1995,
    sqft: 2000,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // New York
  {
    id: "ny_1",
    coordinates: [-74.006, 40.7128],
    owner: "John Smith",
    value: "$1,485,000",
    trustScore: 97,
    address: "123 Broadway, New York, NY",
    propertyType: "Apartment",
    verified: true,
    state: "New York",
    city: "New York",
    yearBuilt: 2018,
    sqft: 1200,
    bedrooms: 2,
    bathrooms: 2,
    marketTrend: "stable",
  },
  {
    id: "ny_2",
    coordinates: [-73.9442, 40.8176],
    owner: "Isabella Rodriguez",
    value: "$685,000",
    trustScore: 89,
    address: "456 Grand Concourse, Bronx, NY",
    propertyType: "Co-op",
    verified: true,
    state: "New York",
    city: "Bronx",
    yearBuilt: 1925,
    sqft: 1800,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // North Carolina
  {
    id: "nc_1",
    coordinates: [-78.6382, 35.7796],
    owner: "Michael Jordan",
    value: "$425,000",
    trustScore: 94,
    address: "123 Tobacco Rd, Raleigh, NC",
    propertyType: "Single Family",
    verified: true,
    state: "North Carolina",
    city: "Raleigh",
    yearBuilt: 2012,
    sqft: 2800,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // North Dakota
  {
    id: "nd_1",
    coordinates: [-100.7837, 46.8083],
    owner: "Ole Olsen",
    value: "$225,000",
    trustScore: 83,
    address: "789 Broadway, Bismarck, ND",
    propertyType: "Single Family",
    verified: true,
    state: "North Dakota",
    city: "Bismarck",
    yearBuilt: 2008,
    sqft: 2100,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Ohio
  {
    id: "oh_1",
    coordinates: [-83.0007, 39.9612],
    owner: "LeBron James",
    value: "$285,000",
    trustScore: 88,
    address: "456 High St, Columbus, OH",
    propertyType: "Single Family",
    verified: true,
    state: "Ohio",
    city: "Columbus",
    yearBuilt: 2010,
    sqft: 2300,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Oklahoma
  {
    id: "ok_1",
    coordinates: [-97.5164, 35.4676],
    owner: "Blake Shelton",
    value: "$195,000",
    trustScore: 85,
    address: "123 Main St, Oklahoma City, OK",
    propertyType: "Ranch",
    verified: true,
    state: "Oklahoma",
    city: "Oklahoma City",
    yearBuilt: 2005,
    sqft: 2200,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Oregon
  {
    id: "or_1",
    coordinates: [-122.6765, 45.5152],
    owner: "Portlandia Smith",
    value: "$525,000",
    trustScore: 91,
    address: "789 Burnside St, Portland, OR",
    propertyType: "Craftsman",
    verified: true,
    state: "Oregon",
    city: "Portland",
    yearBuilt: 1920,
    sqft: 2400,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Pennsylvania
  {
    id: "pa_1",
    coordinates: [-75.1652, 39.9526],
    owner: "Rocky Balboa",
    value: "$385,000",
    trustScore: 90,
    address: "456 Broad St, Philadelphia, PA",
    propertyType: "Rowhouse",
    verified: true,
    state: "Pennsylvania",
    city: "Philadelphia",
    yearBuilt: 1890,
    sqft: 2000,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "up",
  },
  // Rhode Island
  {
    id: "ri_1",
    coordinates: [-71.4128, 41.824],
    owner: "Peter Griffin",
    value: "$425,000",
    trustScore: 87,
    address: "123 Federal Hill, Providence, RI",
    propertyType: "Victorian",
    verified: true,
    state: "Rhode Island",
    city: "Providence",
    yearBuilt: 1895,
    sqft: 2200,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "stable",
  },
  // South Carolina
  {
    id: "sc_1",
    coordinates: [-79.9311, 32.7765],
    owner: "Scarlett O'Hara",
    value: "$485,000",
    trustScore: 92,
    address: "789 King St, Charleston, SC",
    propertyType: "Antebellum",
    verified: true,
    state: "South Carolina",
    city: "Charleston",
    yearBuilt: 1850,
    sqft: 3200,
    bedrooms: 5,
    bathrooms: 4,
    marketTrend: "up",
  },
  // South Dakota
  {
    id: "sd_1",
    coordinates: [-100.351, 44.3683],
    owner: "Laura Ingalls",
    value: "$185,000",
    trustScore: 84,
    address: "456 Main St, Pierre, SD",
    propertyType: "Prairie Style",
    verified: true,
    state: "South Dakota",
    city: "Pierre",
    yearBuilt: 2000,
    sqft: 1900,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Tennessee
  {
    id: "tn_1",
    coordinates: [-86.7816, 36.1627],
    owner: "Dolly Parton",
    value: "$325,000",
    trustScore: 89,
    address: "123 Music Row, Nashville, TN",
    propertyType: "Single Family",
    verified: true,
    state: "Tennessee",
    city: "Nashville",
    yearBuilt: 2008,
    sqft: 2400,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Texas
  {
    id: "tx_1",
    coordinates: [-95.3698, 29.7604],
    owner: "Lisa Rodriguez",
    value: "$385,000",
    trustScore: 91,
    address: "321 Main St, Houston, TX",
    propertyType: "Townhouse",
    verified: true,
    state: "Texas",
    city: "Houston",
    yearBuilt: 2015,
    sqft: 2200,
    bedrooms: 3,
    bathrooms: 3,
    marketTrend: "up",
  },
  {
    id: "tx_2",
    coordinates: [-96.797, 32.7767],
    owner: "J.R. Ewing",
    value: "$485,000",
    trustScore: 93,
    address: "456 Elm St, Dallas, TX",
    propertyType: "Single Family",
    verified: true,
    state: "Texas",
    city: "Dallas",
    yearBuilt: 2018,
    sqft: 2800,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  {
    id: "tx_3",
    coordinates: [-97.7431, 30.2672],
    owner: "Willie Nelson",
    value: "$525,000",
    trustScore: 88,
    address: "789 6th St, Austin, TX",
    propertyType: "Modern",
    verified: true,
    state: "Texas",
    city: "Austin",
    yearBuilt: 2020,
    sqft: 2600,
    bedrooms: 3,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Utah
  {
    id: "ut_1",
    coordinates: [-111.891, 40.7608],
    owner: "Brigham Young III",
    value: "$425,000",
    trustScore: 90,
    address: "123 State St, Salt Lake City, UT",
    propertyType: "Single Family",
    verified: true,
    state: "Utah",
    city: "Salt Lake City",
    yearBuilt: 2012,
    sqft: 2500,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Vermont
  {
    id: "vt_1",
    coordinates: [-72.5806, 44.2601],
    owner: "Ben Jerry",
    value: "$385,000",
    trustScore: 86,
    address: "456 Church St, Montpelier, VT",
    propertyType: "Colonial",
    verified: true,
    state: "Vermont",
    city: "Montpelier",
    yearBuilt: 1985,
    sqft: 2200,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "stable",
  },
  // Virginia
  {
    id: "va_1",
    coordinates: [-77.436, 37.5407],
    owner: "George Washington IV",
    value: "$485,000",
    trustScore: 94,
    address: "789 Monument Ave, Richmond, VA",
    propertyType: "Colonial",
    verified: true,
    state: "Virginia",
    city: "Richmond",
    yearBuilt: 2010,
    sqft: 2600,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "up",
  },
  // Washington
  {
    id: "wa_1",
    coordinates: [-122.3321, 47.6062],
    owner: "Bill Gates Jr.",
    value: "$785,000",
    trustScore: 96,
    address: "123 Pine St, Seattle, WA",
    propertyType: "Modern",
    verified: true,
    state: "Washington",
    city: "Seattle",
    yearBuilt: 2019,
    sqft: 2400,
    bedrooms: 3,
    bathrooms: 3,
    marketTrend: "up",
  },
  // West Virginia
  {
    id: "wv_1",
    coordinates: [-81.6326, 38.3498],
    owner: "John Denver Jr.",
    value: "$165,000",
    trustScore: 82,
    address: "456 Capitol St, Charleston, WV",
    propertyType: "Single Family",
    verified: true,
    state: "West Virginia",
    city: "Charleston",
    yearBuilt: 1995,
    sqft: 1800,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Wisconsin
  {
    id: "wi_1",
    coordinates: [-87.9065, 43.0389],
    owner: "Aaron Rodgers",
    value: "$285,000",
    trustScore: 87,
    address: "789 State St, Milwaukee, WI",
    propertyType: "Bungalow",
    verified: true,
    state: "Wisconsin",
    city: "Milwaukee",
    yearBuilt: 1925,
    sqft: 2000,
    bedrooms: 3,
    bathrooms: 2,
    marketTrend: "stable",
  },
  // Wyoming
  {
    id: "wy_1",
    coordinates: [-104.8197, 41.14],
    owner: "Buffalo Bill",
    value: "$325,000",
    trustScore: 85,
    address: "123 Capitol Ave, Cheyenne, WY",
    propertyType: "Ranch",
    verified: true,
    state: "Wyoming",
    city: "Cheyenne",
    yearBuilt: 2005,
    sqft: 2400,
    bedrooms: 4,
    bathrooms: 3,
    marketTrend: "stable",
  },
]

// Group properties by state for easy filtering
export const propertiesByState = allStateProperties.reduce(
  (acc, property) => {
    if (!acc[property.state]) {
      acc[property.state] = []
    }
    acc[property.state].push(property)
    return acc
  },
  {} as Record<string, Property[]>,
)

// Get property statistics
export const getPropertyStats = () => {
  const totalProperties = allStateProperties.length
  const verifiedProperties = allStateProperties.filter((p) => p.verified).length
  const averageTrustScore = Math.round(allStateProperties.reduce((sum, p) => sum + p.trustScore, 0) / totalProperties)
  const totalValue = allStateProperties.reduce((sum, p) => {
    const value = Number.parseFloat(p.value.replace(/[$,]/g, ""))
    return sum + value
  }, 0)

  return {
    totalProperties,
    verifiedProperties,
    averageTrustScore,
    totalValue: `$${(totalValue / 1000000).toFixed(1)}B`,
    statesWithProperties: Object.keys(propertiesByState).length,
  }
}
